version: '3'
services:
  node-1:
    image: "docker-registry-default.gsa2.lightbend.com/lightbend/exercise_001_cluster_base:1.3.0"
    hostname: "node-1"
    command: "-Dakka.remote.netty.tcp.hostname=node-1 -Djava.library.path=lib -Dcluster-node-configuration.node-hostname=node-1"
    privileged: true
    network_mode: "host"
    extra_hosts:
      - "node-0:192.168.200.10"
      - "node-1:192.168.200.11"
      - "node-2:192.168.200.12"
      - "node-3:192.168.200.13"
      - "node-4:192.168.200.14"